# File provided by azazelm3dj3d
# Learn more: https://github.com/azazelm3dj3d/DockDB

FROM ubuntu:16.04

RUN apt-get update

WORKDIR /shinigami
RUN mkdir /shinigami/project

COPY . /shinigami/project/
